---
# I think that name is ambiguous - is it the name of the user or the machine - so change to host!
 - host: mach-1
   user: js5
   type: windows
   size: 16G
 - host: mach-2
   user: ab6
   type: ubuntu
   size: 8G
 - host: mach-3
   user: mw6
   type: osx
   size: 16G
 - host: mach-5
   user: cs16
   type: osx
   size: 4G
 - host: mach-4
   user: mw8
   type: osx
   size: 8G
